# Generated by Django 6.1.1 on 2026-09-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Registro')),
                ('id_turno', models.CharField(max_length=50, unique=True, verbose_name='ID Turno')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre y Apellido')),
                ('dni', models.CharField(max_length=20, verbose_name='DNI')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('profesional', models.CharField(max_length=100, verbose_name='Profesional')),
                ('fecha', models.DateField(verbose_name='Fecha del Turno')),
                ('hora', models.TimeField(verbose_name='Hora del Turno')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-registro'],
            },
        ),
    ]
